clear all
close all
clc

%input data

time = 1;
X = 4433469.9438;
Y = 362672.7267;
Z = 4556211.6409;
N = 5;
coord_time_wgs84 = zeros(N,4);
coord_time_ECEF = [time X Y Z];
coord_time_ECEF2 = zeros(N,4);
for t = 1:N
    coord_time_ECEF2(t,:) = coord_time_ECEF;
    coord_time_ECEF2(t,1) = t;
end

%check for other coordinates
% Munich: Longitude	11.576124, Latitude	48.137154, Height 520m
% XYZ generated by https://www.oc.nps.edu/oc2902w/coord/llhxyz.htm
x_munich =  4177971;
y_munich =  855800;
z_munich =  4727455;
t = t+1;
coord_time_ECEF2(t,:) = [t x_munich y_munich z_munich];

% coord_time_wgs84(t, :) = xyz2wgs_t(coord_time_ECEF);
% coord_time_wgs84
coord_time_wgs84 = xyz2wgs(coord_time_ECEF2)

